In [1]:
list = ["Thilan",5,99.00,25]
print(list)

['Thilan', 5, 99.0, 25]


In [2]:
print(type(list))

<class 'list'>


In [3]:
print(len(list))

4


In [23]:
array = [1,5,7,8,4]
print(array)

[1, 5, 7, 8, 4]


In [7]:
print(array[0])
print(array[1])

1
5


In [28]:
array.append(8)
print(array)

[1, 5, 7, 8, 4, 8, 8]


In [18]:
array.pop(5)
array

[1, 5, 7, 8, 4]

In [20]:
array.clear()
array

[]

In [24]:
array2 = array.copy()
array2

[1, 5, 7, 8, 4]

In [29]:
array
array.count(8)

3

In [31]:
array.index(8)

3

In [46]:

array2.insert(1,15)

array2

[1, 15, 5, 7, 8, 4, 15, 15]

In [48]:
array2.pop(6)
array2.insert(2,99)
array2

[1, 15, 99, 99, 5, 7, 8, 15]

In [52]:
array2.remove(99)
array2

[99, 5, 7, 8]

In [54]:
array3 = [4,5,8,7,2,5,41,2,5,8,1]
array3.sort()
array3


[1, 2, 2, 4, 5, 5, 5, 7, 8, 8, 41]

In [56]:
import numpy as np
arr = np.array([1,2,5,7,84,1,4])
print(arr)

[ 1  2  5  7 84  1  4]


In [63]:
zeros = np.zeros((3,4))
print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [68]:
matrix = np.array([[4,7,8,5],[5,8,4,2]])
print(matrix[1][0])

5


In [100]:
ranges = np.arange(0,10,3)
print(ranges)

[0 3 6 9]


In [96]:
line_space = np.linspace(0,10,9)
print(line_space)

[ 0.    1.25  2.5   3.75  5.    6.25  7.5   8.75 10.  ]


In [97]:
random = np.random.rand(3, 3)
print(random)

[[0.59793084 0.22881675 0.80603201]
 [0.65195834 0.09388219 0.95338794]
 [0.06745877 0.88809698 0.31531677]]


In [101]:
rows=3
cols=3
list_of_list=[[j for j in range(cols)]for i in range(rows)]
print(list_of_list)

[[0, 1, 2], [0, 1, 2], [0, 1, 2]]


In [103]:
arr3 = np.array([
[[1,4,5,7],[7,5,8,4],[9,6,3,2]],
[[1,5,8,4],[75,5,8,4],[9,6,3,2]] 
    
])
print(arr3)

[[[ 1  4  5  7]
  [ 7  5  8  4]
  [ 9  6  3  2]]

 [[ 1  5  8  4]
  [75  5  8  4]
  [ 9  6  3  2]]]


In [104]:
import numpy as np
rows=3
cols=3
new=3
list_of_list=[[j for j in range(cols)]or i in range(rows)for k in range(new)]
print(list_of_list)

[[0, 1, 2], [0, 1, 2], [0, 1, 2]]


In [113]:
array_1=[[1,2],[3,4]]
array_2=[[1,2],[3,4]]
array_3=[[1,8],[7,4]]
arr_3D = np.array([array_1,array_2,array_3])
print(arr_3D)

[[[1 2]
  [3 4]]

 [[1 2]
  [3 4]]

 [[1 8]
  [7 4]]]


In [115]:
array_1=[[1,2],[3,4]]
array_2=[[1,2],[3,4]]
array_3=[[1,8],[7,4]]
array_4=[[1,7],[6,3]]
arr_4D = np.array([array_1,array_2,array_3,array_4])
print(arr_4D)

[[[1 2]
  [3 4]]

 [[1 2]
  [3 4]]

 [[1 8]
  [7 4]]

 [[1 7]
  [6 3]]]


In [131]:
list_of_list = [[[[j for j in range(3)]for i in range(3)]for n in range(4)]for b in range(4)]
list_of_list

[[[[0, 1, 2], [0, 1, 2], [0, 1, 2]],
  [[0, 1, 2], [0, 1, 2], [0, 1, 2]],
  [[0, 1, 2], [0, 1, 2], [0, 1, 2]],
  [[0, 1, 2], [0, 1, 2], [0, 1, 2]]],
 [[[0, 1, 2], [0, 1, 2], [0, 1, 2]],
  [[0, 1, 2], [0, 1, 2], [0, 1, 2]],
  [[0, 1, 2], [0, 1, 2], [0, 1, 2]],
  [[0, 1, 2], [0, 1, 2], [0, 1, 2]]],
 [[[0, 1, 2], [0, 1, 2], [0, 1, 2]],
  [[0, 1, 2], [0, 1, 2], [0, 1, 2]],
  [[0, 1, 2], [0, 1, 2], [0, 1, 2]],
  [[0, 1, 2], [0, 1, 2], [0, 1, 2]]],
 [[[0, 1, 2], [0, 1, 2], [0, 1, 2]],
  [[0, 1, 2], [0, 1, 2], [0, 1, 2]],
  [[0, 1, 2], [0, 1, 2], [0, 1, 2]],
  [[0, 1, 2], [0, 1, 2], [0, 1, 2]]]]

In [135]:
#Exersize
#1
#create an evenly spaced array of numbers based on given start and stop values

evenly_array = np.linspace(0,10,6)
print(evenly_array)

[ 0.  2.  4.  6.  8. 10.]


In [136]:
#2
#create an array of zeros that be filled with data later
zerosss = np.zeros((3,4))
zerosss

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [138]:
#3
#create an array of ones
ones = np.ones((5,5))
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [140]:
#4
#create array of rando, floats between zero and one
ra = np.random.rand(3,3)
print(ra)

[[0.51369713 0.40218018 0.51789445]
 [0.28595291 0.89155665 0.69927509]
 [0.5722256  0.3242218  0.40869489]]


In [208]:
#5
#create 1D array and insert the values 1,2,3,4,5 and access the following elements
#1st
#second
#range of elements from 1 to 3rd
#range of elements from 2nd element
#range of elements from index=2

array1d = [1,2,3,4,5]
print("First_Element",array1d[0])
print("Second_Element",array1d[1])
print("Range_from 1 to 3:",array1d[:3])
print("Range_from 2nd element:",array1d[1:])
print("Range_from index 2:",array1d[2:])

First_Element 1
Second_Element 2
Range_from 1 to 3: [1, 2, 3]
Range_from 2nd element: [2, 3, 4, 5]
Range_from index 2: [3, 4, 5]


In [184]:
#6create 2d array and try to access following elements
#1 row 2nd column element
#2nd row elements
#3rd column elements
#range of elements in 1st and 2nd row with 2nd and 3rd column

arr2d = [[1,2,3,4,5,6],[7,8,59,10,11,12],[13,14,15,16,17,18]]
print("First_row and Second Column Element:",arr2d[0][1])
print("Second_row Element:",arr2d[1])
print("Third_Column Element:",[i[2] for i in arr2d])
print("Range_of_Elements:",[i[1:3] for i in arr2d[0:2]])

First_row and Second Column Element: 2
Second_row Element: [7, 8, 59, 10, 11, 12]
Third_Column Element: [3, 59, 15]
Range_of_Elements: [[2, 3], [8, 59]]


In [209]:
#7
#create a 1D array mamke it within order by axis wise

x = np.array([88,2,5,4,71,1])
print(np.sort(x))


[ 1  2  4  5 71 88]


In [210]:
#8
#read 1D array and insert the values 1,9,2,5,3 and check whether the elements in array are grater than 5. and print those element as seperate list

x = int(input("Enter number of elements:"))

arr = []

for i in range(x):
    element = int(input(f"Enter element {i+1}:"))
    arr.append(element)

print("Your Array is:",arr)

grater_list = []
for i in arr:
    if i > 5:
        grater_list.append(i)     

print("Grater_than_5_elements list:",grater_list)


Enter number of elements: 5
Enter element 1: 1
Enter element 2: 9
Enter element 3: 2
Enter element 4: 5
Enter element 5: 3


Your Array is: [1, 9, 2, 5, 3]
Grater_than_5_elements list: [9]


In [211]:
#9 
#create 1D array and insert values from 0 to 20 within 3 gap space and find the values which are divide by 2. and 
#replace 0 in array which are not satisfied the condition

In [222]:
arr_space = np.arange(0,20,3)
print(arr_space)

divide_list = []
for i in arr_space:
   if i%2 == 0:
       divide_list.append(int(i))

print("Divided_List:",divide_list)


[ 0  3  6  9 12 15 18]
Divided_List: [0, 6, 12, 18]
